### ISSUE TITLE
don't work on 28.2

### ISSUE THREAD

**Issue by 11111000000** [Ladicle/flymake-posframe#3]
error

Error in post-command-hook (flymake-posframe-display): (wrong-type-argument stringp nil)

**Comment by articuluxe** [comment]
I assume you are using eglot?

This code:
`           :string (concat (propertize
			    (pcase (flymake--diag-type diag)
                                 (:error flymake-posframe-error-prefix)
                                 (:warning flymake-posframe-warning-prefix)
                                 (:note flymake-posframe-note-prefix))
                               'face 'warning)
			   (flymake--diag-text diag)))
`

needs to add handlers for 'eglot-error', 'eglot-warning' and 'eglot-note'.  Currently the prefix does not match the eglot-specific flymake errors, and errors out.

Is this repo still alive?  Would an MR be accepted?

**Comment by articuluxe** [comment]
Well, I've created an MR, hope it can be merged: https://github.com/Ladicle/flymake-posframe/pull/4

**Comment by garyo** [comment]
I'm getting the same error, for the same reason -- using eglot. Would like to see this merged.

**Comment by Ladicle** [comment]
fixed in https://github.com/Ladicle/flymake-posframe/commit/4b65fd0b55262b52177548a15a949f34b9c49cbb
